name: reflective
author: Stijn Van Bael <stijn.van.bael@appify.be>
homepage: https://github.com/stijnvanbael/reflection
version: 0.1.6
description: A fluent reflection API
environment:
  sdk: "<=3.0.0"
dev_dependencies:
  test: any
  collection: any
