name: reflective
homepage: https://github.com/stijnvanbael/reflection
version: 0.1.9
description: A fluent reflection API
environment:
  sdk: "<=3.0.0"
dev_dependencies:
  test: any
  collection: any
