name: reflection
author: Stijn Van Bael <stijnvanbael@gmail.com>
homepage: https://github.com/stijnvanbael/reflection
version: 0.1.0
description: A fluent reflection API
environment:
  sdk: "<=3.0.0"
dev_dependencies:
  test: any
  collection: any
